Vertical login
boltgolt/howdy pull request #627
Opened 2021-12-31 14:00 UTC by matan-arnon

This allows logging in when notebook is held vertically as requested in #624 
Uses xlib to get screen dimensions (allowing to assume what orientation screen is in).
If screen is portrait instead of standard landscape, alternates rotating images 90 degrees clockwise and counter-clockwise before scanning for face.

2022-01-02 14:21 UTC, boltgolt requested changes
Thank you very much for these changes! This will help quite a few people i think. However, the dependency on X server and the possibilities of false positives worry me a bit. Maybe reading from a config value and only then importing anything X related would be better?

2022-01-02 14:21 UTC, boltgolt commented on howdy/debian/postinst
> +handleStatus(subprocess.call(["pip3", "install", "--upgrade", "python3-xlib"]))
This feels like an external dependency for something relatively few users are going to use, maybe we can make it a config option and ask users to install this themselves? That would also remove a point of failure in installation

2022-01-02 14:21 UTC, boltgolt commented on howdy/src/compare.py
> +import Xlib.display as display
What happens when a user is running Wayland?

2022-01-02 14:21 UTC, boltgolt commented on howdy/src/compare.py
> +if screen_height > screen_width:
I'm worried this will trigger for people using external vertical monitors, i really think this should be disabled by config option by default

2022-01-02 17:55 UTC, matan-arnon commented
@boltgolt, makes sense to me. Could add it to the config file and then instead of importing X, just automatically rotate the images when checking for faces. Would make authentication slower for the few people that use the feature but would eliminate the X dependency.
What do you think?

2022-01-03 11:53 UTC, boltgolt commented
Hm yes that would also work and be a bit simpler to implement, but would be a shame to throw some of your work away. We could just tell people in install the dependency in the config:

```ini
# Rotate captured frames so faces are upright
# Can be either false, auto, or an array of angles like 0,90,180
# Please install the required dependency before enabling auto mode: 
#  pip3 install python3-xlib
rotate = auto
```

You don't have to implement the array part at all of course i'm just thinking out loud here

2022-01-16 17:17 UTC, boltgolt approved these changes

2022-01-16 17:18 UTC, merged

2022-01-16 17:19 UTC, boltgolt commented
Thank you so much! Will be released together with the other beta v3 changes